% Takes the angles for each joint and the distance to the marker tip.
% Adds them to the table of the DH parameters for transformations.
% "angles" must be a 1x7 matrix of radians
% "tip_pos" must be in meters

function y = get_parameters(angles, tip_pos)
ang = angles;
tip = tip_pos;

    %d          r       theta       alpha
y = [0.27035    0.069   ang(1)      -pi/2;...
     0          0       ang(2)+pi/2 pi/2;...
     0.36435    0.069   ang(3)      -pi/2;...
     0          0       ang(4)      pi/2;...
     0.37429    0.1     ang(5)      -pi/2;...
     0          0       ang(6)      pi/2;...
     tip        0       ang(7)      0];